# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x44\x61taInfo.proto\"P\n\x04\x44\x61ta\x12\x12\n\x08intValue\x18\x02 \x01(\x05H\x00\x12\x14\n\nfloatValue\x18\x03 \x01(\x02H\x00\x12\x15\n\x0bstringValue\x18\x04 \x01(\tH\x00\x42\x07\n\x05value\"$\n\x08\x44\x61taInfo\x12\x18\n\texcelData\x18\x01 \x03(\x0b\x32\x05.Data**\n\x08\x44\x61taType\x12\x07\n\x03INT\x10\x00\x12\t\n\x05\x46LOAT\x10\x01\x12\n\n\x06STRING\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DataInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATATYPE']._serialized_start=138
  _globals['_DATATYPE']._serialized_end=180
  _globals['_DATA']._serialized_start=18
  _globals['_DATA']._serialized_end=98
  _globals['_DATAINFO']._serialized_start=100
  _globals['_DATAINFO']._serialized_end=136
# @@protoc_insertion_point(module_scope)
