# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreatePostWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreatePostsForm(object):
    def setupUi(self, CreatePostsForm):
        CreatePostsForm.setObjectName("CreatePostsForm")
        CreatePostsForm.resize(360, 170)
        CreatePostsForm.setMinimumSize(QtCore.QSize(360, 100))
        self.PlostTypeComboBox = QtWidgets.QComboBox(CreatePostsForm)
        self.PlostTypeComboBox.setGeometry(QtCore.QRect(95, 20, 170, 22))
        self.PlostTypeComboBox.setStyleSheet("QComboBox {\n"
"    text-align: center;\n"
"}")
        self.PlostTypeComboBox.setCurrentText("")
        self.PlostTypeComboBox.setObjectName("PlostTypeComboBox")
        self.CreateBtn = QtWidgets.QPushButton(CreatePostsForm)
        self.CreateBtn.setGeometry(QtCore.QRect(95, 140, 170, 22))
        self.CreateBtn.setObjectName("CreateBtn")
        self.layoutWidget = QtWidgets.QWidget(CreatePostsForm)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 57, 331, 74))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.PostsNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.PostsNameLineEdit.setObjectName("PostsNameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.PostsNameLineEdit)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.PostsCategoriesLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.PostsCategoriesLineEdit.setObjectName("PostsCategoriesLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.PostsCategoriesLineEdit)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.PostsTagLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.PostsTagLineEdit.setObjectName("PostsTagLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.PostsTagLineEdit)

        self.retranslateUi(CreatePostsForm)
        QtCore.QMetaObject.connectSlotsByName(CreatePostsForm)

    def retranslateUi(self, CreatePostsForm):
        _translate = QtCore.QCoreApplication.translate
        CreatePostsForm.setWindowTitle(_translate("CreatePostsForm", "Form"))
        self.CreateBtn.setText(_translate("CreatePostsForm", "创建"))
        self.label.setText(_translate("CreatePostsForm", "文章名字"))
        self.label_2.setText(_translate("CreatePostsForm", "文章种类(categories)"))
        self.label_3.setText(_translate("CreatePostsForm", "文章标签(Tag)"))
