# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TipWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TipWidget(object):
    def setupUi(self, TipWidget):
        TipWidget.setObjectName("TipWidget")
        TipWidget.setWindowModality(QtCore.Qt.WindowModal)
        TipWidget.setEnabled(False)
        TipWidget.resize(200, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TipWidget.sizePolicy().hasHeightForWidth())
        TipWidget.setSizePolicy(sizePolicy)
        TipWidget.setMinimumSize(QtCore.QSize(200, 100))
        TipWidget.setMaximumSize(QtCore.QSize(200, 100))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("TWTools.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TipWidget.setWindowIcon(icon)
        TipWidget.setAutoFillBackground(True)
        self.gridLayout = QtWidgets.QGridLayout(TipWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(TipWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(TipWidget)
        QtCore.QMetaObject.connectSlotsByName(TipWidget)

    def retranslateUi(self, TipWidget):
        _translate = QtCore.QCoreApplication.translate
        TipWidget.setWindowTitle(_translate("TipWidget", "提示"))
        self.label.setText(_translate("TipWidget", "TextLabel"))
