# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(320, 180)
        MainWidget.setMinimumSize(QtCore.QSize(320, 180))
        MainWidget.setMaximumSize(QtCore.QSize(320, 180))
        self.StatusLabel = QtWidgets.QLabel(MainWidget)
        self.StatusLabel.setGeometry(QtCore.QRect(20, 10, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.StatusLabel.setFont(font)
        self.StatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StatusLabel.setObjectName("StatusLabel")
        self.layoutWidget = QtWidgets.QWidget(MainWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 80, 282, 82))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StatueButton = QtWidgets.QPushButton(self.layoutWidget)
        self.StatueButton.setMinimumSize(QtCore.QSize(80, 80))
        self.StatueButton.setObjectName("StatueButton")
        self.horizontalLayout.addWidget(self.StatueButton)
        self.DJDHBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.DJDHBtn.setMinimumSize(QtCore.QSize(80, 80))
        self.DJDHBtn.setObjectName("DJDHBtn")
        self.horizontalLayout.addWidget(self.DJDHBtn)
        self.SSSQBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.SSSQBtn.setMinimumSize(QtCore.QSize(80, 80))
        self.SSSQBtn.setObjectName("SSSQBtn")
        self.horizontalLayout.addWidget(self.SSSQBtn)

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "抓包工具"))
        self.StatusLabel.setText(_translate("MainWidget", "暂停中..."))
        self.StatueButton.setText(_translate("MainWidget", "启动"))
        self.DJDHBtn.setText(_translate("MainWidget", "抓取\n"
"大江大河"))
        self.SSSQBtn.setText(_translate("MainWidget", "抓取\n"
"实时水情"))
